### PR TITLE
[WIP] Implement bans

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by caseif** [comment]
What was the verdict on this PR?

**Comment by nallar** [comment]
Looks like it's missing some implementation here: https://github.com/LapisBlue/Pore/pull/23/files#diff-c9a78ead0f03eddda755835892724a01R115

> // Correct me if I'm wrong, but Sponge doesn't seem to have the ability to change bans.
> // Perhaps remove the original Ban and create a new one?

Compilation failure here: https://github.com/LapisBlue/Pore/pull/23/files#diff-c9a78ead0f03eddda755835892724a01R65

> PoreBanEntry.java:65: error: cannot find symbol
        this.expiration = handle.getExpirationDate().**orNull**();

**Comment by jamierocks** [comment]
The implementation is missing, because I am lazy. Actually it's not that hard but because I was in a rush and Sponge doesn't have this functionality.

**Comment by caseif** [comment]
Closing this for now in light of #29.

**Pull request closed without merging**
