### PR TITLE
My brane couldn't anglish.

### PR DESCRIPTION
**Pull request by phase**
Small typo.

### CODE REVIEW

**Comment by Minecrell** [comment]
Sponge is actually a (Forge) mod so both things are wrong

**Comment by phase** [comment]
I don't want to keep it at just "mod", as then it might be confusing on what it's a mod for.

**Comment by caseif** [comment]
This part of the README *should* probably be revised, but currently this PR retains the grammatical ambiguity (in that "which serves..." may appear to refer to Sponge rather than Pore.

Additionally, it should be kept in mind that Pore isn't limited to the official implementation (I.e. the Forge mod).

**Comment by phase** [comment]
@caseif Too much ambiguity...

**Comment by jamierocks** [comment]
to be honest anyone looking at pore source, should know what Sponge is xD

**Comment by phase** [comment]
@jamierocks Anyone looking at LapisBlue should know what Sponge is.

**Comment by jamierocks** [comment]
Change it to <code>Pore is a plugin for the up-and-coming SpongeAPI which acts as a bridge to provide compatibility for Bukkit plugins on servers implementing SpongeAPI.</code>

**Comment by caseif** [comment]
@jamierocks Eh, that sounds a little redundant. How about:

`Pore is a plugin for the up-and-coming SpongeAPI built to provide compatibility for Bukkit plugins on the platform.`

**Comment by AesenV** [comment]
Maybe:
```markdown
Pore is a complete reimplementation of the Bukkit API on top of Sponge API.
It aims to allow you to run any Bukkit plugins on any Sponge server, be it
Quartz, Glowstone, the official Forge mod, or others. **Pore is currently
incomplete, and is not known to run any Bukkit plugins.** Contributions
are welcomed and encouraged.`
```

This replaces both mini-paragraphs with one paragraph.
We may also want to mention that Pore will probably never run any plugins that require NMS.

**Comment by caseif** [comment]
@AesenV That's a bit long-winded IMO. I'd vouch for keeping it short and sweet.

**Comment by phase** [comment]
@caseif I'm going to have like 30 commits in this once it's over...

**Comment by caseif** [comment]
@phase I would use this to keep it more concise:

`Pore is a plugin for the up-and-coming SpongeAPI built to provide compatibility for Bukkit plugins on the platform. Please note that this project is still under heavy development and **is not yet considered functional**. Currently, no Bukkit plugins are verified to be supported.`

**Comment by caseif** [comment]
[Merged!](https://github.com/LapisBlue/Pore/commit/3bdcf07c6d6c2597b3d63dc3ed51a6531681ee9f)

**Comment by phase** [comment]
@caseif Why didn't you merge this pull request?

**Comment by Minecrell** [comment]
@phase It was merged, just rebased into one commit before being merged, that's why GitHub is not displaying this correctly

**Comment by phase** [comment]
@Minecrell Gotcha!

**Pull request closed without merging**
